### ISSUE TITLE
Botão de voltar não está fechando conexão com o servidor (web socket)

### ISSUE THREAD

**Issue by r-e-g-e** [jrpolesi/bandeirantes#1]
O botão de voltar dentro do jogo está não esta fechando a conexão feita com o web socket, causando players fantasmas.

Passos para reproduzir:
1- Defina um nome
2- Entre em uma sala
3- Clique em voltar
4- Defina novamente um nome
5- Entre na mesma sala escolinha anteriormente

**Comment by jrpolesi** [comment]
Este botão não deve fechar a conexão, ele está aí para ser usado durante o desenvolvimento da tela
